export const suggestions: string[] = [
  "Apple",
  "Apricot",
  "Banana",
  "Blackberry",
  "Blueberry",
  "Cherry",
  "Cranberry",
  "Date",
  "Dragonfruit",
  "Elderberry",
  "Fig",
  "Grape",
  "Grapefruit",
  "Guava",
  "Kiwi",
  "Lemon",
  "Lime",
  "Lychee",
  "Mango",
  "Nectarine",
  "Orange",
  "Papaya",
  "Passionfruit",
  "Peach",
  "Pear",
  "Pineapple",
  "Plum",
  "Pomegranate",
  "Raspberry",
  "Strawberry",
  "Tangerine",
  "Watermelon",
  "Avocado",
  "Coconut",
  "Mandarin",
  "Mulberry",
  "Olive",
  "Persimmon",
  "Jackfruit",
  "Starfruit",
  "Gooseberry",
  "Goji Berry",
  "Acai",
  "Tamarind",
  "Soursop",
  "Cantaloupe",
  "Honeydew",
  "Jasmine",
  "Pawpaw",
  "Quince",
  "Fig",
  "Date Palm",
  "Rhubarb",
  "Blackcurrant",
  "Redcurrant",
  "White Grapes",
  "Zucchini",
  "Tomato",
  "Paprika",
  "Cucumber",
  "Carrot",
  "Asparagus",
  "Celery",
  "Bell Pepper",
  "Chili Pepper",
  "Eggplant",
  "Okra",
  "Artichoke",
  "Fennel",
  "Radish",
  "Leek",
  "Brussels Sprout",
  "Kale",
  "Spinach",
  "Mustard Greens",
  "Collard Greens",
  "Bok Choy",
  "Turnip",
  "Sweet Potato",
  "Yam",
  "Pumpkin",
  "Butternut Squash",
  "Acorn Squash",
  "Parsnip",
  "Chard",
  "Cabbage",
  "Cauliflower",
  "Broccoli",
  "Mushroom",
  "Portobello",
  "Shiitake",
  "Chanterelle",
  "Oyster Mushroom",
  "Truffle",
  "Reishi",
  "Morel",
  "Enoki",
  "Lion's Mane",
  "Tarragon",
  "Basil",
  "Coriander",
  "Cilantro",
  "Dill",
  "Oregano",
  "Thyme",
  "Rosemary",
  "Mint",
  "Sage",
  "Lavender",
  "Chives",
  "Fennel",
  "Marjoram",
  "Bay Leaf",
  "Parsley",
  "Turmeric",
  "Ginger",
  "Garlic",
  "Shallot",
  "Onion",
  "Scallion",
  "Chili",
  "Curry Leaf",
  "Lemongrass",
  "Wasabi",
  "Horseradish",
  "Cinnamon",
  "Nutmeg",
  "Clove",
  "Cardamom",
  "Cumin",
  "Paprika",
  "Turmeric",
  "Saffron",
  "Tamarind",
  "Curry Powder",
  "Fennel Seeds",
  "Fenugreek",
  "Anise",
  "Star Anise",
  "Pepper",
  "Black Pepper",
  "White Pepper",
  "Pink Peppercorns",
  "Sea Salt",
  "Kosher Salt",
  "Himalayan Salt",
  "Rock Salt",
  "Miso",
  "Soy Sauce",
  "Teriyaki",
  "Worcestershire Sauce",
  "Barbecue Sauce",
  "Hot Sauce",
  "Vinegar",
  "Balsamic Vinegar",
  "Apple Cider Vinegar",
  "Rice Vinegar",
  "Wine Vinegar",
  "Maple Syrup",
  "Honey",
  "Agave Syrup",
  "Molasses",
  "Corn Syrup",
  "Brown Sugar",
  "Coconut Sugar",
  "Stevia",
  "Xylitol",
  "Monk Fruit Sweetener",
  "Aspartame",
  "Sucralose",
  "Erythritol",
  "Sorghum Syrup",
  "Date Syrup",
  "Coconut Milk",
  "Almond Milk",
  "Oat Milk",
  "Rice Milk",
  "Cashew Milk",
  "Macadamia Milk",
  "Soy Milk",
  "Hemp Milk",
  "Coconut Water",
  "Almond Butter",
  "Peanut Butter",
  "Cashew Butter",
  "Tahini",
  "Sunflower Butter",
  "Soy Sauce",
  "Worcestershire Sauce",
  "Miso Paste",
  "Sriracha",
  "Vegan Mayonnaise",
  "Vegenaise",
  "Mustard",
  "Ketchup",
  "Hot Sauce",
  "Barbecue Sauce",
  "Chutney",
  "Relish",
  "Aioli",
  "Hoisin Sauce",
  "Teriyaki Sauce",
  "Tzatziki",
  "Pesto",
  "Coconut Cream",
  "Soy Yogurt",
  "Almond Yogurt",
  "Coconut Yogurt",
  "Cashew Yogurt",
  "Tofu",
  "Tempeh",
  "Seitan",
  "Chia Seeds",
  "Flax Seeds",
  "Hemp Seeds",
  "Pumpkin Seeds",
  "Sunflower Seeds",
  "Sesame Seeds",
  "Almonds",
  "Cashews",
  "Pistachios",
  "Walnuts",
  "Macadamia Nuts",
  "Brazil Nuts",
  "Pecans",
  "Hazelnuts",
  "Peanuts",
  "Pine Nuts",
  "Coconut Flakes",
  "Coconut Oil",
  "Olive Oil",
  "Avocado Oil",
  "Almond Oil",
  "Sunflower Oil",
  "Peanut Oil",
  "Canola Oil",
  "Vegetable Oil",
  "Safflower Oil",
  "Sesame Oil",
  "Ghee",
  "Butter",
  "Margarine",
  "Lard",
  "Tallow",
  "Vegetable Shortening",
  "Crisco",
  "Coconut Flour",
  "Almond Flour",
  "Rice Flour",
  "Tapioca Flour",
  "Chickpea Flour",
  "Oat Flour",
  "Cornstarch",
  "Arrowroot Powder",
  "Potato Starch",
  "Sweet Rice Flour",
  "Wheat Flour",
  "Whole Wheat Flour",
  "Spelt Flour",
  "Barley Flour",
  "Millet Flour",
  "Teff Flour",
  "Amaranth Flour",
  "Sorghum Flour",
  "Coconut Sugar",
  "Maple Syrup",
  "Agave Nectar",
  "Molasses",
  "Stevia",
  "Erythritol",
  "Xylitol",
  "Monk Fruit",
  "Coconut Water",
  "Almond Milk",
  "Oat Milk",
  "Rice Milk",
  "Soy Milk",
  "Hemp Milk",
  "Cashew Milk",
  "Macadamia Milk",
  "Samsung",
];

export const homePageSuggestions: string[] = [
  "Welcome to Our Website",
  "Latest News",
  "Featured Articles",
  "Trending Topics",
  "Popular Products",
  "New Arrivals",
  "Customer Reviews",
  "Special Offers",
  "Join Our Community",
  "Sign Up Now",
  "Learn More",
  "About Us",
  "Services We Offer",
  "Top Picks for You",
  "Recommended for You",
  "Follow Us on Social Media",
  "Subscribe to Our Newsletter",
  "Help & Support",
  "FAQs",
  "Shop Now",
  "Browse Categories",
  "Latest Blog Posts",
  "Our Mission",
  "Contact Us",
  "Read Testimonials",
  "Exclusive Content",
  "Privacy Policy",
  "Terms & Conditions",
  "Site Map",
  "Accessibility Features",
  "Partners & Affiliates",
  "Gift Cards",
  "Track Your Order",
  "Sign In",
  "Create an Account",
  "Visit Our Store",
  "Download Our App",
  "Get Started",
  "Discover More",
  "Top Sellers",
  "Sales & Discounts",
  "Customer Satisfaction",
  "Our Values",
  "Community Engagement",
];

export const settingsPageSuggestions: string[] = [
  "Change Username",
  "Change Email",
  "Change Password",
  "Notification Preferences",
  "Account Security",
  "Language Settings",
  "Privacy Settings",
  "Manage Subscriptions",
  "Privacy Policy",
  "Terms of Service",
  "Two-Factor Authentication",
  "Connected Accounts",
  "Email Notifications",
  "Push Notifications",
  "Save Changes",
  "Delete Account",
  "Account Recovery",
  "Dark Mode",
  "Light Mode",
  "Font Size",
  "Theme Customization",
  "Update Profile Picture",
  "Language Preference",
  "Time Zone Settings",
  "Location Settings",
  "Billing Information",
  "Payment Methods",
  "View Payment History",
  "Manage Addresses",
  "Order History",
  "Account Activity Log",
  "Help & Support",
  "Contact Support",
  "Check for Updates",
  "App Version",
  "Accessibility Options",
  "Data Management",
  "Export Data",
  "Reset Preferences",
  "App Permissions",
  "Notifications Sound",
  "Reset Password",
  "Account Verification",
  "Sign Out",
  "Enable Dark Mode",
  "Language Support",
  "Change Security Questions",
  "Subscription Settings",
  "Privacy & Data",
];
